### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by racic** [akoken/Jirabox#11]
Hi, 
I wanted to try Jirabox on my phone because it looks promising. 
I provided the authentication details and I get error message:
"Opps! Server could not authorize your account - please try again"
This is not a username/password problem as there was a different message for that. On the same phone I can login to jira via Internet Explorer. Could it be certificate problem?
racic

**Comment by akoken** [comment]
Hi @racic,
Server url could be wrong. If you are sure that url is correct, rest api setting, which is required for Jirabox, could be disabled. Make sure the 'Allow Remote API Calls' is turned ON under Administration > General Configuration or contact your Jira server administrator.

Thanks,
a
